// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/decimal/[num].tsx";
import * as $1 from "./routes/decimal/index.tsx";
import * as $2 from "./routes/decimal/range/[from].tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/DecimalSearch.tsx";

const manifest = {
  routes: {
    "./routes/decimal/[num].tsx": $0,
    "./routes/decimal/index.tsx": $1,
    "./routes/decimal/range/[from].tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/DecimalSearch.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
