// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/decimal/[num].tsx";
import * as $1 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/decimal/[num].tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
